Repository Look-at-the-Weather/Backend, pull requests merged in 2024-09, with the labels that each got.

#65 RefreshToekn 관리 방식 수정
  src/main/java/com/WearWeather/wear/domain/auth/controller/AuthController.java
  src/main/java/com/WearWeather/wear/domain/auth/dto/response/LoginResponse.java
  src/main/java/com/WearWeather/wear/domain/auth/dto/response/TokenResponse.java
  src/main/java/com/WearWeather/wear/domain/auth/service/AuthService.java
  src/main/java/com/WearWeather/wear/domain/location/service/LocationService.java
  src/main/java/com/WearWeather/wear/domain/oauth/controller/OAuthController.java
  src/main/java/com/WearWeather/wear/domain/oauth/service/OAuthLoginService.java
  src/main/java/com/WearWeather/wear/global/jwt/TokenProvider.java
  src/test/java/com/WearWeather/wear/domain/auth/AuthServiceTest.java
Labels: refactor

#69 변경된 요구사항에 따른 게시글 생성,수정,삭제 리팩토링
  src/main/java/com/WearWeather/wear/domain/post/dto/request/PostCreateRequest.java
  src/main/java/com/WearWeather/wear/domain/post/dto/request/PostUpdateRequest.java
  src/main/java/com/WearWeather/wear/domain/post/entity/Post.java
  src/main/java/com/WearWeather/wear/domain/post/service/PostService.java
  src/main/java/com/WearWeather/wear/domain/postHidden/repository/PostHiddenRepository.java
  src/main/java/com/WearWeather/wear/domain/postHidden/service/PostHiddenService.java
  src/main/java/com/WearWeather/wear/domain/postImage/dto/request/PostImageRequest.java
  src/main/java/com/WearWeather/wear/domain/postImage/repository/PostImageRepository.java
  src/main/java/com/WearWeather/wear/domain/postImage/service/PostImageService.java
  src/main/java/com/WearWeather/wear/domain/postLike/repository/LikeRepository.java
  src/main/java/com/WearWeather/wear/domain/postReport/repository/PostReportRepository.java
  src/main/java/com/WearWeather/wear/domain/postReport/service/PostReportService.java
  src/main/java/com/WearWeather/wear/domain/postTag/repository/PostTagRepository.java
  src/main/java/com/WearWeather/wear/domain/postTag/service/PostTagService.java
  src/main/java/com/WearWeather/wear/domain/storage/controller/AwsS3Controller.java
  src/main/java/com/WearWeather/wear/global/exception/ErrorCode.java
Labels: refactor

#73 게시글 이미지 필드 유효성 강화 및 불필요한 이미지 자동 삭제하는 스케줄러 추가
  src/main/java/com/WearWeather/wear/domain/post/dto/request/PostCreateRequest.java
  src/main/java/com/WearWeather/wear/domain/post/dto/request/PostUpdateRequest.java
  src/main/java/com/WearWeather/wear/domain/postImage/repository/PostImageRepository.java
  src/main/java/com/WearWeather/wear/domain/postImage/scheduler/postImageScheduler.java
  src/main/java/com/WearWeather/wear/domain/postImage/service/PostImageService.java
  src/main/java/com/WearWeather/wear/domain/user/entity/User.java
  src/main/java/com/WearWeather/wear/global/exception/ErrorCode.java
Labels: bug

#68 회원 탈퇴 구현
  src/main/java/com/WearWeather/wear/domain/auth/service/AuthService.java
  src/main/java/com/WearWeather/wear/domain/oauth/domain/oauth/OAuthClient.java
  src/main/java/com/WearWeather/wear/domain/oauth/domain/oauth/OAuthUserInfo.java
  src/main/java/com/WearWeather/wear/domain/oauth/infrastructure/kakao/KaKaoApiClient.java
  src/main/java/com/WearWeather/wear/domain/oauth/infrastructure/kakao/KaKaoUserInfo.java
  src/main/java/com/WearWeather/wear/domain/oauth/infrastructure/kakao/dto/KakaoUserDto.java
  src/main/java/com/WearWeather/wear/domain/oauth/infrastructure/kakao/entity/KakaoUser.java
  src/main/java/com/WearWeather/wear/domain/oauth/infrastructure/kakao/repository/KakaoUserRepository.java
  src/main/java/com/WearWeather/wear/domain/oauth/infrastructure/kakao/service/KakaoUserService.java
  src/main/java/com/WearWeather/wear/domain/oauth/service/OAuthLoginService.java
  src/main/java/com/WearWeather/wear/domain/oauth/service/RequestOAuthUnlinkService.java
  src/main/java/com/WearWeather/wear/domain/user/controller/UserController.java
  src/main/java/com/WearWeather/wear/domain/user/controller/UserDeleteController.java
  src/main/java/com/WearWeather/wear/domain/user/dto/request/DeleteReasonRequest.java
  src/main/java/com/WearWeather/wear/domain/user/entity/User.java
  src/main/java/com/WearWeather/wear/domain/user/entity/UserDelete.java
  src/main/java/com/WearWeather/wear/domain/user/enums/DeleteReason.java
  src/main/java/com/WearWeather/wear/domain/user/repository/UserDeleteRepository.java
  src/main/java/com/WearWeather/wear/domain/user/repository/UserRepository.java
  src/main/java/com/WearWeather/wear/domain/user/service/UserDeleteService.java
  src/main/java/com/WearWeather/wear/domain/user/service/UserService.java
  src/main/java/com/WearWeather/wear/global/common/ResponseMessage.java
  src/main/java/com/WearWeather/wear/global/config/SecurityConfig.java
  src/main/java/com/WearWeather/wear/global/exception/ErrorCode.java
  src/main/java/com/WearWeather/wear/global/jwt/CustomUserDetailsService.java
  src/test/java/com/WearWeather/wear/domain/auth/AuthServiceTest.java
  src/test/java/com/WearWeather/wear/domain/user/UserServiceTest.java
Labels: documentation
